const crearNovedad = (cover, titulo, autor, descripcion, url) => {
  const novedad = document.createElement('div');

  const detallesNovedad = `<div class="books" id="books-economia">
    <img class="cover" src="${cover}" alt="${titulo}">
    <div class="books-details">
        <h2 class="books-titulo">${titulo}</h2>
        <h3 class="books-autor">${autor}</h3>
        <p class="books-descripcion">${descripcion}</p>
        <li class="button-acceso" id="button-acceso-economia"><a href="${url}" target="_blank">Consulta aquí</a></li>
    </div>`;

  novedad.innerHTML = detallesNovedad;
  return novedad
};

const totalNovedades = document.querySelector("[data-novedades]");

const diccionario = {
  libros: [
    {id: '12',cover: '/img/portadas/12_por.png',titulo: 'La agroindustria procesadora de cereales de Colombia, factores internos y externos inductores de cambio', autor: 'Álvaro Castillo Niño ',tema: 'Economía y administración',descripcion: 'En Colombia hasta las fechas relativamente recientes, la agricultura, y la agroindustria, especialmente la dedicada la producción de alimentos, era tenida como una actividad de segunda clase. En una lectura en 1884 en el Ateneo de Bogotá, Salvador Camacho Roldán, al dirigirse a su auditoria, formado seguramente por los entonces considerados "intelectuales" manifiesto que, "se interrumpirá talvez para decirme: ese es asunto de comer y de beber, de papas y de maíz, especulación materialista, indigna de ser tardada en salón, en donde el público quiere oír cosas nuevas e interesantes.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254921'},
    {id: '40',cover: '/img/portadas/40_por.png',titulo: 'El estado emprendedor: la oposición público-privado y sus mitos ', autor: 'Mariana Mazzucato',tema: 'Economía y administración',descripcion: 'Mariana Mazzucaro desmonta este falso mito para desmostrar que el estado, lejos de limitarse a intervenir en el mercado para subsanar posibles errores o abusos, es en realidad una organización audaz, capaz de asumir la inversiones de mayor riesgo , y un facilitador clave de las innovaciones tecnológicas que impulsan el crecimiento económico',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254931'},
    {id: '42',cover: '/img/portadas/42_por.png',titulo: 'Un pequeño empujón: el impulso que necesitas para tomar decisiones sobre salud, dinero y felicidad ', autor: 'Richard H. Thaler, Cass R. Sustein',tema: 'Economía y administración',descripcion: 'En Un pequeño empujón, considerado ya un clásico y uno de los mejores libros sobre economía y política de las últimas décadas, Cass R. Sunstein y Richard H. Thaler, premio Nobel de Economía, observan cómo nuestras percepciones y decisiones dependen del modo en que se organizan ante nosotros las diferentes opciones. Gobiernos y empresas, pero también padres, profesores y médicos, se convierten así en una especie de «arquitectos de la elección. Las personas e instituciones públicas o privadas pueden incentivar sin mermar la libertad de elección de los ciudadanos, y obtener así grandes logros en relación con la sanidad pública, las finanzas o la igualdad',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254950'},
    {id: '45',cover: '/img/portadas/45_por.png',titulo: 'De Silicon Valley a tu negocio: innovación, data e inteligencia artificial ', autor: 'David Villaseca Morales, Susana González Pérez',tema: 'Economía y administración',descripcion: 'Este manual permite conectar con las soluciones, herramientas y prácticas de innovación utilizadas en Silicon Valley, colocando en el centro las necesidades de las personas y profundizando en las claves tecnológicas de la transformación hacia un negocio más inteligente. El cloud computing ha supuesto una verdadera revolución en el proceso de transformación digital, maximizando las capacidades y reduciendo los costes',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254937'},
    {id: '52',cover: '/img/portadas/52_por.png',titulo: 'Charlas TED: la guía oficial de TED para hablar en público', autor: 'Chris Anderson',tema: 'Economía y administración',descripcion: 'Desde que empezaron a publicarse en Internet, las Charlas TED (TED Talks) cambiaron la forma en que se habla en público, la manera como se divulga el conocimiento y los escenarios en los que se comparten ideas a escala global. A comienzos de los años 2000, cuando se empezaron a realizar y a transmitir a través de la red, el estilo TED se convirtió en una mecánica de cómo presentar y hablar frente a audiencias de todo el mundo.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=253960'},
    {id: '54',cover: '/img/portadas/54_por.png',titulo: 'La nueva milla extra: cómo elevar el engagement y conseguir resultados extraordinarios', autor: 'Ricardo Matamala',tema: 'Economía y administración',descripcion: 'La milla extra no es un concepto asociado a más tiempo o esfuerzo en el trabajo; es un tema integral que implica disponer de la mayor energía en lo que hacemos, es deliberada y conscientemente querer ofrecer a las organizaciones la mejor versión de nosotros mismos.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254955'},
    {id: '55',cover: '/img/portadas/55_por.png',titulo: 'El club de las 5 de la mañana: controla tus mañanas, impulsa tu vida ', autor: 'Robin Sharma',tema: 'Economía y administración',descripcion: 'Robin Sharma es uno de los mayores expertos mundiales en liderazgo y desempeño. Desarrolló el concepto del Club de las 5 de la mañana hace más de veinte años a partir de los revolucionarios hábitos que han permitido a sus clientes incrementar su productividad, mejorar su salud y afrontar con serenidad la extremadamente compleja época en que vivimos. Este libro, de profundo impacto personal, nos descubrirá las rutinas que han hecho posible que muchas personas alcancen grandes resulta- dos al tiempo que nuestra felicidad y vitalidad aumenta. A través de una entretenida historia de dos personas que conocen al mismo tiempo a un excéntrico magnate que termina por convertirse en su mentor, El Club de las 5 de la mañana nos muestra',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254532'},
    {id: '57',cover: '/img/portadas/57_por.png',titulo: 'Un inmueble al año no hace daño: estrategias para generar ingresos invirtiendo en bienes raíces', autor: 'Carlos Devis',tema: 'Economía y administración',descripcion: 'Invertir en bienes raíces es fácil si uno dispone del dinero para ello. Pero para convertirlo en un negocio rentable el dinero no basta, se requiere conocimiento y actitud. Dicho en otras palabras, no se trata de lo que tengas en tu bolsillo, sino de lo que tengas en tu cabeza.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254960'},
    {id: '58',cover: '/img/portadas/58_por.png',titulo: '¡Si lo hubiera sabido antes!: cómo lograr la paz y libertad financiera', autor: 'Carlos Devis',tema: 'Economía y administración',descripcion: 'Ganar más, gastar menos, ahorrar más e invertir bien, es algo que todos sabemos y queremos, pues es similar a comer sano o bajar de peso... ¡lo quisiéramos! Pero ¿cómo hacerlo bien y mantenerlo a largo plazo?',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254961'},
    {id: '59',cover: '/img/portadas/59_por.png',titulo: 'Innovación para cabezas cuadradas', autor: 'Edgar Guillermo Solano',tema: 'Economía y administración',descripcion: 'Innovación para cabezas cuadradas no es un libro, es una pintura colorida de finos trazos que cuando la tenemos al frente nos invita a ser apreciada, a que seamos creativos y nunca dejemos de tener capacidad de asombro en una búsqueda permanente de lo posible; en su lienzo plasma historias humanas y cotidianas que se desprenden de la experiencia y el conocimiento que con generosidad nos entrega su autor Edgar Guillermo Solano.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254963'},
    {id: '62',cover: '/img/portadas/62_por.png',titulo: 'El valor de las cosas: quién produce y quién gana en la economía global', autor: 'Mariana Mazzucato',tema: 'Economía y administración',descripcion: '¿En qué mundo queremos vivir? Mariana Mazzucato, la economista del momento, prende la mecha de un debate necesario.«Mucho ojo con Mazzucato, la economista más temible del mundo.» Helen Rumbelow, The Times ¿Quién crea realmente la riqueza? ¿Qué actividades la impulsan? ¿Cuáles se limitan a extraerla? ¿Cuáles la destruyen? Nuestras economías tienden a premiar la extracción de valor antes que su creación -el proceso productivo que verdaderamente impulsa una economía y una sociedad saludables-, y la diferencia entre ambos conceptos se ha desdibujado de manera notable. A partir de ejemplos que van desde Silicon Valley hasta el sector financiero pasando por las grandes farmacéuticas, Mariana Mazzucato muestra de manera magistral cómo las nociones borrosas que tenemos del valor han permitido a ciertos actores de la economía retratarse a sí mismos como generadores de valor, mientras que en realidad se limitan a mover el existente o, lo que es peor, a destruirlo.',url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=241845'},
  ]
};

diccionario.libros.forEach(libro => {
  const nuevaNovedad = crearNovedad(libro.cover, libro.titulo, libro.autor, libro.descripcion, libro.url);
  totalNovedades.appendChild(nuevaNovedad);
});