const crearNovedad = (cover, titulo, autor, descripcion, url) => {
  const novedad = document.createElement('div');

  const detallesNovedad = `<div class="books" id="books-derecho">
    <img class="cover" src="${cover}" alt="${titulo}">
    <div class="books-details">
        <h2 class="books-titulo">${titulo}</h2>
        <h3 class="books-autor">${autor}</h3>
        <p class="books-descripcion">${descripcion}</p>
        <li class="button-acceso" id="button-acceso-derecho"><a href="${url}" target="_blank">Consulta aquí</a></li>
    </div>`;

  novedad.innerHTML = detallesNovedad;
  return novedad
};

const totalNovedades = document.querySelector("[data-novedades]");

const diccionario = {
  libros: [
    { id: '1', cover: '/2023-09/img/portadas/1.png', titulo: 'Uno siempre cambia al amor de su vida: por otro amor o por otra vida', autor: 'Amalia Andrade', tema: 'AMOR', descripcion: 'Que enamorarse es y será siempre eso que me pasó a su lado. Pero amar es mejor.', url: 'https://ugc.overdrive.com/media/5426485' },
    { id: '2', cover: '/2023-09/img/portadas/2.png', titulo: 'Del amor y otros demonios', autor: 'Gabriel García Márquez', tema: 'AMOR', descripcion: 'No tenía ni un instante sin pensar en ella, que la vida era ella a toda hora y en todas partes, como solo Dios tenía el derecho y el poder de serlo y que el gozo supremo de su corazón seria morirse con ella.', url: 'https://ugc.overdrive.com/media/5301884' },
    { id: '4', cover: '/2023-09/img/portadas/4.png', titulo: 'Tokio blues: Norwegian Wood', autor: 'Haruki Murakami', tema: 'AMOR', descripcion: 'Hay dos tipos de personas: los que son capaces de abrir su corazón a los demás y los que no. Tú te cuentas entre los primeros. Puedes abrir tu corazón siempre y cuando quieras hacerlo.', url: 'https://ugc.overdrive.com/media/2019310' },
    { id: '5', cover: '/2023-09/img/portadas/5.png', titulo: 'Hombres sin mujeres', autor: 'Haruki Murakami', tema: 'AMOR', descripcion: 'Pero es que entre nosotros siempre existió algo así como un botón mal abrochado. Creo que podrías ser feliz de una manera mucho más normal y corriente.', url: 'https://ugc.overdrive.com/media/2261477' },
    { id: '6', cover: '/2023-09/img/portadas/6.png', titulo: 'Pecado', autor: 'Laura Restrepo', tema: 'AMOR', descripcion: 'Cada pecado trae consigo su correspondiente culpa, pero también su gota de alivio.', url: 'https://ugc.overdrive.com/media/2602199' },
    { id: '8', cover: '/2023-09/img/portadas/8.png', titulo: 'Cartas eróticas', autor: 'Nicolas Bersihand', tema: 'AMOR', descripcion: 'Quiero creer que sí. Que aún existen individuos sin miedo, que desafían a la muerte y se lanzan al abismo del placer. Y, además, reviven ese goce con su amante, su amigo o con su padre. Yo qué sé. Son locos románticos. El mundo está a sus pies.', url: 'https://ugc.overdrive.com/media/9379956' },
    { id: '9', cover: '/2023-09/img/portadas/9.png', titulo: 'Llámame por tu nombre', autor: 'André Aciman', tema: 'AMOR', descripcion: 'Y pensar que casi me enamoro de la piel de sus manos, de su pecho, de sus pies que nunca habían pisado tierra áspera en su vida y de sus ojos que cuando te dedicaban la otra mirada, la de semblante dulce, te portaban el milagro de la resurrección.', url: 'https://ugc.overdrive.com/media/4000688' },
    { id: '13', cover: '/2023-09/img/portadas/13.png', titulo: 'Justine o los infortunios de la virtud', autor: 'Marqués De Sade', tema: 'AMOR', descripcion: 'Amar es una cosa muy diferente a disfrutar; la prueba está en que se ama todos los días sin disfrutar, y con mayor frecuencia aún se disfruta sin amar.', url: 'https://ugc.overdrive.com/media/6039513' },
    { id: '14', cover: '/2023-09/img/portadas/14.png', titulo: 'El amor en los tiempos del cólera', autor: 'Gabriel García Márquez', tema: 'AMOR', descripcion: 'Y la miró por última vez para siempre jamás con los ojos más luminosos, más tristes y más agradecidos que ella no le vio nunca en medio siglo de vida en común, y alcanzó a decirle con el último aliento: - Sólo Dios sabe cuánto te quise.', url: 'https://ugc.overdrive.com/media/4567533' },
    { id: '15', cover: '/2023-09/img/portadas/15.png', titulo: 'Boulevard: libro 1', autor: 'Flor M. Salvador', tema: 'AMOR', descripcion: '—¿Sabes? —La miró con dureza—. Deja que se rían de lo patética que creen que eres, al final de cuentas todos terminamos igual… —Dio una calada a su cigarro y dejó escapar el humo—, en un boulevard de los sueños rotos.', url: 'https://ugc.overdrive.com/media/8749698' },
    { id: '16', cover: '/2023-09/img/portadas/16.png', titulo: 'Boulevard. libro 2', autor: 'Flor M. Salvador', tema: 'AMOR', descripcion: 'No sabes en qué momento te enamoras, creo que no existe un instante exacto, simplemente pasa, te enamoras de su rostro, de su personalidad, de sus ojos, de su humor, de sus características, de sus defectos...Son las circunstancias en donde ya no importa nada y tratas de mejorar por ella.', url: 'https://ugc.overdrive.com/media/8891969' },
    { id: '17', cover: '/2023-09/img/portadas/17.png', titulo: 'Como agua para chocolate', autor: 'Laura Esquivel', tema: 'AMOR', descripcion: '- ¿Estás más enamorada de él que de mí? - No te lo puedo contestar, tampoco lo sé. Cuando tú no estás aquí, pienso que es a él a quien quiero, pero cuando te veo, todo cambia. A tu lado me siento tranquila, segura, en paz... pero no sé... no sé... Discúlpame por decirte todo esto.', url: 'https://ugc.overdrive.com/media/2353864' },
    { id: '18', cover: '/2023-09/img/portadas/18.png', titulo: 'La abadía de Northanger', autor: 'Jane Austen', tema: 'AMOR', descripcion: 'Su corazón se hallaba entonces inundado de alegría, despreocupado e independiente, ansioso de saborear placeres aún desconocidos y libre de toda culpa. Así era ella antes, pero ahora… estaba completamente cambiada.', url: 'https://ugc.overdrive.com/media/4133676' },
    { id: '19', cover: '/2023-09/img/portadas/19.png', titulo: 'Orgullo y prejuicio', autor: 'Jane Austen', tema: 'AMOR', descripcion: 'Mis afectos y deseos no han cambiado, pero una palabra suya me silenciará para siempre.', url: 'https://ugc.overdrive.com/media/4000692' },
    { id: '20', cover: '/2023-09/img/portadas/20.png', titulo: 'Tristán e Isolda', autor: 'Anónimo', tema: 'AMOR', descripcion: '- ¿No creéis que hay más cosas en la vida? - ¿Más cosas - Algo más que el deber y la muerte? ¿Por qué tenemos sentimientos y no podemos desarrollarlos? ¿Por qué desear cosas si no pueden ser nuestras?', url: 'https://ugc.overdrive.com/media/6112942' },
    { id: '21', cover: '/2023-09/img/portadas/21.png', titulo: 'La letra escarlata', autor: 'Nathaniel Hawthorne', tema: 'AMOR', descripcion: 'Ningún hombre, durante un período considerable, puede llevar una cara ante sí mismo y otra ante la multitud, sin quedar finalmente perplejo sobre cuál puede ser la verdadera.', url: 'https://ugc.overdrive.com/media/4504654' },
    { id: '22', cover: '/2023-09/img/portadas/22.png', titulo: 'Bajo la misma estrella', autor: 'John Green', tema: 'AMOR', descripcion: 'Parecía una eternidad, como si hubiéramos estado juntos una breve, pero infinita eternidad. Hay infinitos más grandes que otros infinitos.', url: 'https://ugc.overdrive.com/media/3136267' },
    { id: '23', cover: '/2023-09/img/portadas/23.png', titulo: 'Poesía reunida', autor: 'José Asunción Silva', tema: 'AMOR', descripcion: 'Sufre este mal: ... pensar..., ésa es la causa de su grave y sutil melancolía.', url: 'https://ugc.overdrive.com/media/5321213' },
    { id: '24', cover: '/2023-09/img/portadas/24.png', titulo: 'El libro de versos', autor: 'José Asunción Silva', tema: 'AMOR', descripcion: '¡Azul el cielo! ¡Azul!… Y la suave, brisa que pasa, dice: ¡Reíd! ¡Cantad! ¡Amad! ¡La vida es fiesta!, ¡Es calor, es pasión, es movimiento!', url: 'https://ugc.overdrive.com/media/264336' },
    { id: '25', cover: '/2023-09/img/portadas/25.png', titulo: 'La tregua', autor: 'Mario Benedetti', tema: 'AMOR', descripcion: 'Entonces sentí una tremenda opresión en el pecho, una opresión en la que no parecía estar afectado ningún órgano físico, pero que era algo asfixiante, insoportable. Ahí, en el pecho, cerca de la garganta, ahí debe estar el alma, hecha un ovillo.', url: 'https://ugc.overdrive.com/media/2010150' },
    { id: '26', cover: '/2023-09/img/portadas/26.png', titulo: 'Cumbres borrascosas', autor: 'Emily Brontë', tema: 'AMOR', descripcion: 'El mundo es una odiosa colección de recuerdos que claman que ella existió y yo la perdí.', url: 'https://ugc.overdrive.com/media/9533494' },
    { id: '29', cover: '/2023-09/img/portadas/29.png', titulo: 'Arráncame la vida', autor: 'Ángeles Masttreta', tema: 'AMOR', descripcion: 'Empecé a volverme una mujer que va de las penas a las carcajadas sin ningún trámite, que siempre está esperando que algo le pase, lo que sea, menos las mañanas iguales. Odiaba la paz, me daba miedo.', url: 'https://ugc.overdrive.com/media/5635775' },
    { id: '30', cover: '/2023-09/img/portadas/30.png', titulo: 'Crónica de una muerte anunciada', autor: 'Gabriel García Márquez', tema: 'AMOR', descripcion: 'Dueña por primera vez de su destino, descubrió entonces que el odio y el amor son pasiones recíprocas.', url: 'https://ugc.overdrive.com/media/2983041' },
    { id: '33', cover: '/2023-09/img/portadas/33.png', titulo: 'La vida mentirosa de los adultos', autor: 'Elena Ferrante', tema: 'AMOR', descripcion: 'En pocas palabras, ¿qué ocurría en el mundo de los adultos, en la cabeza de personas muy razonables, en sus cuerpos llenos de saber? ¿Qué los transformaba en los animales menos dignos de confianza, peores que los reptiles?', url: 'https://ugc.overdrive.com/media/5600590' },
    { id: '34', cover: '/2023-09/img/portadas/34.png', titulo: 'Malaherba', autor: 'Manuel Jabois, Martiño Rivas', tema: 'AMOR', descripcion: 'Y bien sabe Dios que es más peligrosa la pena que el odio, porque el odio puede destruir lo que odias, pero la pena lo destruye todo.', url: 'https://ugc.overdrive.com/media/4783969' },
    { id: '40', cover: '/2023-09/img/portadas/40.png', titulo: 'Strange', autor: 'Alex Mírez', tema: 'AMOR', descripcion: 'Existía gente con buena autoestima y luego estaba Nolan con su autoestima y amor propio volando con fuerza por la estratosfera. Para ayudarlo, mi madre era como su fan #1.', url: 'https://ugc.overdrive.com/media/9097655' },
    { id: '41', cover: '/2023-09/img/portadas/41.png', titulo: 'Mentiras y secretos: perfectos mentirosos 1', autor: 'Alex Mírez', tema: 'AMOR', descripcion: 'tres perfectos mentirosos salieron un día: uno se fue a decir muchas mentiras, otro fue a guardar un gran secreto, y el ultimo como siempre se esmeró en fingir que era uno de ellos.', url: 'https://ugc.overdrive.com/media/8150345' },
    { id: '42', cover: '/2023-09/img/portadas/42.png', titulo: 'Peligros y verdades: perfectos mentirosos 2', autor: 'Alex Mírez', tema: 'AMOR', descripcion: 'No es real que sientas algo por dos personas. Eso solo significa que te gusta una, pero que intentas engañarte con la otra.', url: 'https://ugc.overdrive.com/media/8150347' },
    { id: '43', cover: '/2023-09/img/portadas/43.png', titulo: 'La mirada de Humilda', autor: 'Alonso Sánchez Baute', tema: 'AMOR', descripcion: 'Esa tarde el universo conspiraba en mi contra... porque en ese momento K., alzó con las dos manos al animal, quizá con temor de que se le cayera, y lo llevó a la altura de su cara. Es hembra, dijo con los ojos chispeando de alborozo mientras la cachorra le lamía los labios.', url: 'https://ugc.overdrive.com/media/8994991' },
    { id: '44', cover: '/2023-09/img/portadas/44.png', titulo: 'Las malas', autor: 'Camila Sosa Villada', tema: 'AMOR', descripcion: 'La desidia de la gente ese día me ofreció una revelación: estaba sola, este cuerpo era mi responsabilidad. Ninguna distracción, ningún amor, ningún argumento, por irrefutable que fuese, podían quitarme la responsabilidad de mi cuerpo. Entonces me olvidé del miedo.', url: 'https://ugc.overdrive.com/media/4636321' },
    { id: '47', cover: '/2023-09/img/portadas/47.png', titulo: 'Adicta a ti', autor: 'Laurelin Paige', tema: 'AMOR', descripcion: '- Así que soy como las demás. -No, no lo eres. - Su voz se volvió más tensa-. Ya te lo dije, mi deseo de hacerte daño no es mayor que mi necesidad de conseguirte.', url: 'https://ugc.overdrive.com/media/1974249' },
    { id: '48', cover: '/2023-09/img/portadas/48.png', titulo: 'Al sur de la frontera, al oeste del Sol', autor: 'Haruki Murakami', tema: 'AMOR', descripcion: 'Nadie se sumerge en ninguna aventura esperando resultados mediocres. La gente, pese a tener un chasco nueve de cada diez veces, desea tener al menos una experiencia suprema, aunque sólo sea una vez. Y eso es lo que mueve el mundo. Eso es el arte, supongo.', url: 'https://ugc.overdrive.com/media/2019270' },
    { id: '49', cover: '/2023-09/img/portadas/49.png', titulo: 'Amor: amor y deseo según Isabel Allende: sus mejores páginas', autor: 'Isabel Allende', tema: 'AMOR', descripcion: 'El amor nos vuelve buenos. No importa a quién amemos, tampoco importa ser correspondidos o si la relación es duradera. Basta la experiencia de amar, eso nos transforma.', url: 'https://ugc.overdrive.com/media/2601999' },
    { id: '50', cover: '/2023-09/img/portadas/50.png', titulo: 'Cinco esquinas', autor: 'Mario Vargas Llosa', tema: 'AMOR', descripcion: 'Se besaron con avidez y desesperación, primero en los labios y, luego, abriendo las bocas, confundiendo sus lenguas, intercambiando sus salivas, mientras las manos de cada una le quitaban —le arranchaban— a la otra el camisón hasta quedar desnudas y enredadas; giraban.', url: 'https://ugc.overdrive.com/media/2602014' },
    { id: '51', cover: '/2023-09/img/portadas/51.png', titulo: 'Cinco esquinas (Audiolibro)', autor: 'Mario Vargas Llosa', tema: 'AMOR', descripcion: 'Podría satisfacer su curiosidad morbosa, su apetito chismográfico, ese placer inmenso que produce a los mediocres, la mayoría de la humanidad, saber que los famosos, los respetables, las celebridades, los decentes, están hechos también del mismo barro mugriento que los demás.', url: 'https://ugc.overdrive.com/media/4939501' },
    { id: '52', cover: '/2023-09/img/portadas/52.png', titulo: 'Cincuenta sombras de Grey', autor: 'E.L. James & Pilar De la Peña Minguell', tema: 'AMOR', descripcion: 'Un hombre siempre puede tener esperanzas, Anastasia, incluso sueña, y a veces los sueños se hacen realidad.', url: 'https://ugc.overdrive.com/media/6294850' },
    { id: '53', cover: '/2023-09/img/portadas/53.png', titulo: 'Ciudades de papel', autor: 'John Green & Alberto Santillán', tema: 'AMOR', descripcion: 'Es muy difícil para cualquier persona mostrarse como es, y tan difícil para nosotros enseñarle a alguien como nos sentimos.', url: 'https://ugc.overdrive.com/media/2353850' },
    { id: '54', cover: '/2023-09/img/portadas/54.png', titulo: 'Diario de una pasión, El cuaderno de Noah', autor: 'Nicholas Sparks', tema: 'AMOR', descripcion: 'Los amores de verano terminan por todo tipo de razones, pero al fin y al cabo todos tienen algo en común: son estrellas fugaces. Un espectacular momento de luz celestial, una efímera luz de la eternidad que en un instante se va.', url: 'https://ugc.overdrive.com/media/4678036' },
    { id: '56', cover: '/2023-09/img/portadas/56.png', titulo: 'Morsamor: peregrinaciones heroicas y lances de amor y fortuna de Miguel de Zuheros y Tiburcio de Simahonda', autor: 'Juan Valera', tema: 'AMOR', descripcion: 'Todo ser humano, considerado exterior y someramente, es indigno de memoria si no ha logrado por virtud de sus hechos o de sus palabras, habladas o escritas, influir poderosamente en los sucesos de su época, haciendo ruido en el mundo.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/ereader/ugc/171112?page=1' },
    { id: '57', cover: '/2023-09/img/portadas/57.png', titulo: 'Dos amores', autor: 'Cirilo Villaverde', tema: 'AMOR', descripcion: 'Que la esclavitud tiene fuerza de trastornar la noción de lo justo y de lo injusto en el espíritu del amo; que embota la sensibilidad humana; que afloja los lazos sociales más estrechos; que debilita el sentimiento de la propia dignidad y aun oscurece las ideas del honor.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/ereader/ugc/171158?page=1' },
    { id: '58', cover: '/2023-09/img/portadas/58.png', titulo: 'El sentido del amor', autor: 'Héctor Anaya', tema: 'AMOR', descripcion: 'Nos aferrábamos en nuestra media desnudez a no ser los mártires del amor telúrico y libresco, porque lo que más teníamos es que los temblorcitos terminarían por hacer que se vinieran abajo los libros y nosotros quedáramos sepultados.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/lc/ugc/titulos/39355' },
    { id: '59', cover: '/2023-09/img/portadas/59.png', titulo: 'El amante japonés', autor: 'Isabel Allende', tema: 'AMOR', descripcion: 'Y quien diga que todo fuego, tarde o temprano se apaga solo, se equivoca... Hay pasiones que son incendios hasta que las ahoga el destino de un zarpazo, y aun así, quedan brasas calientes listas para arder penas les den oxígeno.', url: 'https://ugc.overdrive.com/media/2276139' },
    { id: '60', cover: '/2023-09/img/portadas/60.png', titulo: 'El amor huele a café', autor: 'Nieves García Bautista', tema: 'AMOR', descripcion: 'Pero lo que más odiaba en este mundo eran los espejos. Esos artilugios del demonio habían sido creados, sin duda, para admiración de las bellas y tortura de las feas.', url: 'https://ugc.overdrive.com/media/1657528' },
    { id: '61', cover: '/2023-09/img/portadas/61.png', titulo: 'El mapa de los afectos', autor: 'Ana Merino', tema: 'AMOR', descripcion: 'Dicen que cuando el desamparo es muy profundo el cerebro se inventa a Dios.', url: 'https://ugc.overdrive.com/media/5506234' },
    { id: '62', cover: '/2023-09/img/portadas/62.png', titulo: 'No hay burlas con el amor', autor: 'Pedro Calderón de la Barca', tema: 'AMOR', descripcion: 'Con este engaño, llevado en las alas del deseo, lisonjeado de la noche, aplaudido del silencio, festejado de las sombras, a quien más favores debo que al sol, que a luz, que al día, vivo de saber que muero.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/ereader/ugc/36134?page=1' },
    { id: '63', cover: '/2023-09/img/portadas/63.png', titulo: 'El perfume', autor: 'Patrick Süskind', tema: 'AMOR', descripcion: 'Lo que codiciaba era la fragancia de ciertas personas: aquellas, extremadamente raras, que inspiran amor.', url: 'https://ugc.overdrive.com/media/2010830' },
    { id: '64', cover: '/2023-09/img/portadas/64.png', titulo: 'Hay momentos que deberían ser eternos', autor: 'Megan Maxwell', tema: 'AMOR', descripcion: 'Dios pudo haber creado al hombre antes que a la mujer, pero siempre hay un borrador antes de la obra maestra.', url: 'https://ugc.overdrive.com/media/6353013' },
    { id: '66', cover: '/2023-09/img/portadas/66.png', titulo: 'Para antes del olvido', autor: 'Tomás González', tema: 'AMOR', descripcion: 'Hay personas que inmediatamente después de muertas crean una resonancia mucho mayor que la que jamás lograron mientras estuvieron vivas.', url: 'https://ugc.overdrive.com/media/3246316' },
    { id: '67', cover: '/2023-09/img/portadas/67.png', titulo: 'Pídeme lo que quieras, ahora y siempre', autor: 'Megan Maxwell', tema: 'AMOR', descripcion: 'No puedes marcharte de mi lado sin darme una explicación y esperar que yo no me vuelva loco de preocupación. Prefiero que llames a mi puerta y me digas «¡Adiós!» a creer que estás y no estés. ¿De acuerdo?', url: 'https://ugc.overdrive.com/media/4003220' },
    { id: '68', cover: '/2023-09/img/portadas/68.png', titulo: 'Las 25 derivaciones del amor en femenino', autor: 'Marta Sampietro Biarge', tema: 'AMOR', descripcion: '—Anda, anda, que dices, que estoy muy liada yo ahora y muy enamorada, y no sé qué voy a hacer con esta maraña en mi cabeza. Aunque... Pensándomelo bien... Ven el domingo a casa.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/lc/ugc/titulos/105063' },
    { id: '69', cover: '/2023-09/img/portadas/69.png', titulo: 'Querido Harry: cartas de amor, agradecimiento y magia', autor: 'álvaro Toledo García', tema: 'AMOR', descripcion: 'Para mí, tu historia es lo más grande que siempre he tenido. Ha sido mi refugio cuando las cosas no iban bien, ha sido mi mayor fuente de inspiración creativa, ha sido lo que ha dado fundamento a mi existencia, lo que llenaba mi día a día.', url: 'https://elibro-net.bibliodigital.ugc.edu.co/es/ereader/ugc/105081?page=1' },
    { id: '70', cover: '/2023-09/img/portadas/70.png', titulo: 'A tres metros sobre el cielo', autor: 'Federico Moccia', tema: 'AMOR', descripcion: 'El miedo es algo terrible; te impide disfrutar de los mejores momentos. Si no sabes vencerlo, es como una especie de maldición.', url: 'https://ugc.overdrive.com/media/2028715' },
    { id: '71', cover: '/2023-09/img/portadas/71.png', titulo: 'A tres metros sobre el cielo + Tengo ganas de ti + Tres veces tú (pack)', autor: 'Federico Moccia', tema: 'AMOR', descripcion: 'Un beso lo es todo. Un beso es la verdad. Sin demasiados ejercicios de estilo, sin retorcimientos extremos, sin enroscamientos funambulísticos. Natural, lo más bonito.', url: 'https://ugc.overdrive.com/media/3139482' },
    { id: '72', cover: '/2023-09/img/portadas/72.png', titulo: 'Yo antes de ti', autor: 'Jojo Moyes', tema: 'AMOR', descripcion: 'Si eso es lo que él realmente quiere, aprovecha el tiempo que le queda, haz que sea especial.', url: 'https://ugc.overdrive.com/media/1976842' },
    { id: '73', cover: '/2023-09/img/portadas/73.png', titulo: 'Un grito de amor desde el centro del mundo', autor: 'Kyoichi Katayama', tema: 'AMOR', descripcion: 'Y, algún día, los mensajeros de la luna me arrebatarían a mi princesa. Entonces sólo me quedaría un tiempo tan largo como la vida eterna.', url: 'https://ugc.overdrive.com/media/3725793' },
    { id: '74', cover: '/2023-09/img/portadas/74.png', titulo: '¡Que viva la música!', autor: 'Andrés Caicedo Estela', tema: 'AMOR', descripcion: 'Supe que había perdido mi tiempo desandando un camino que ya había ganado cruzando una sola calle. Me sentí desubicada y sin ganas de un Norte que pisaba por pura torpeza. El amor de Adasa quedó en mi corazón. Eché candela rumbo al Sur salvaje, en donde se escucha mi canción.', url: 'https://ugc.overdrive.com/media/5028501' },
    { id: '75', cover: '/2023-09/img/portadas/75.png', titulo: '1984', autor: 'George Orwell', tema: 'AMOR', descripcion: 'Doble pensar significa el poder de tener dos creencias contradictorias en la mente de uno simultáneamente y aceptar ambas.', url: 'https://ugc.overdrive.com/media/2079454' },
    { id: '76', cover: '/2023-09/img/portadas/76.png', titulo: 'Forastera', autor: 'Diana Gabaldon', tema: 'AMOR', descripcion: 'Dije: «Señor, si alguna vez en mi vida he tenido valor, dámelo ahora. Permíteme ser lo bastante valiente para no caer de rodillas y rogarle que se quede».', url: 'https://ugc.overdrive.com/media/5615572' },
    { id: '81', cover: '/2023-09/img/portadas/81.png', titulo: 'La música del corazón', autor: 'Brittainy C. Cherry', tema: 'AMOR', descripcion: 'Con el tiempo y a base de sufrimiento, comprendí la realidad más dura de todas: el amor es algo que no se puede forzar, por más que lo intentes... Lo único que tienes es el poder sobre tu alma y el poder de descubrir lo que hace que te lata el corazón.', url: 'https://ugc.overdrive.com/media/5361568' },
  ]
};

diccionario.libros.forEach(libro => {
  const nuevaNovedad = crearNovedad(libro.cover, libro.titulo, libro.autor, libro.descripcion, libro.url);
  totalNovedades.appendChild(nuevaNovedad);
});