const crearNovedad = (cover, titulo, autor, descripcion, url) => {
  const novedad = document.createElement('div');

  const detallesNovedad = `<div class="books" id="books-economia">
    <img class="cover" src="${cover}" alt="${titulo}">
    <div class="books-details">
        <h2 class="books-titulo">${titulo}</h2>
        <h3 class="books-autor">${autor}</h3>
        <p class="books-descripcion">${descripcion}</p>
        <li class="button-acceso" id="button-acceso-economia"><a href="${url}" target="_blank">Consulta aquí</a></li>
    </div>`;

  novedad.innerHTML = detallesNovedad;
  return novedad
};

const totalNovedades = document.querySelector("[data-novedades]");

const diccionario = {
  libros: [
    { id: '16', cover: '/2023-08/img/portadas/16.png', titulo: 'Panorama Social de América Latina y el Caribe 2022: la transformación de la educación como base para el desarrollo sostenible', autor: 'Naciones Unidas Comisión Económica para América Latina y el Caribe. CEPAL', tema: 'Ciencias Económicas y Empresariales', descripcion: 'La CEPAL presentó su informe Panorama Social de América Latina 2010, el que está dedicado a analizar las brechas de inequidad existentes en la región, en particular las que enfrentan la juventud y la niñez. El informe analiza la condición de pobreza, desigualdad y ciclo de vida; la educación frente a la reproducción intergeneracional de la desigualdad y la exclusión: situación y desafíos en América Latina; el gasto público social en América Latina: tendencias generales e inversión en el desarrollo de capacidades de las nuevas generaciones; la economía generacional, sistemas de transferencias y desigualdad en América Latina y, las transferencias públicas en etapas tempranas del ciclo vital: un desafío clave para el combate intertemporal a la desigualdad', url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254849' },
    { id: '17', cover: '/2023-08/img/portadas/17.png', titulo: 'The MBA handbook: Academic and professional skills for mastering management', autor: 'Sheila Cameron', tema: 'Ciencias Económicas y Empresariales', descripcion: 'Este manual se escribió por la frustración que sentía al ver que tantos estudiantes sacaban tan poco provecho de sus estudios de MBA a pesar de una enorme inversión de tiempo y esfuerzo. Treinta años de enseñanza después, el mundo es muy diferente. La globalización masiva facilitada por la explosión digital, la crisis financiera, la pandemia, el (lento) creciente reconocimiento de una emergencia climática (y mucho más) han cambiado el mundo tal y como lo conocíamos entonces. También se ha producido una explosión de titulaciones de posgrado en gestión, y el texto es relevante sea cual sea el curso, si está relacionado de algún modo con la gestión o los negocios.', url: 'https://www-ebooks7-24-com.bibliodigital.ugc.edu.co/?il=15427' },
    { id: '18', cover: '/2023-08/img/portadas/18.png', titulo: 'International Finance: Theory Policy', autor: 'Paul R. Krugman', tema: 'Ciencias Económicas y Empresariales', descripcion: 'De la reciente experiencia pandémica se pueden extraer muchas lecciones, pero una de ellas es la importancia de una perspectiva internacional para analizar acontecimientos de trascendencia económica mundial y las respuestas de los países. El propósito de este libro es dotar a los estudiantes de herramientas intelectuales para comprender las implicaciones económicas de la interdependencia mundial.', url: 'https://www-ebooks7-24-com.bibliodigital.ugc.edu.co/?il=19828' },
    { id: '22', cover: '/2023-08/img/portadas/22.png', titulo: 'Marketing: An Introduction', autor: 'Gary Armstrong & Philip Kotler', tema: 'Ciencias Económicas y Empresariales', descripcion: 'La decimoquinta edición de Marketing: Una introducción refleja las principales tendencias y las fuerzas cambiantes que afectan al marketing en esta era digital de valor, compromiso y relaciones con el cliente. Éstos son sólo algunos de los principales cambios nuevos y continuos que encontrará en esta edición.', url: 'https://www-ebooks7-24-com.bibliodigital.ugc.edu.co/?il=21031' },
    { id: '23', cover: '/2023-08/img/portadas/23.png', titulo: 'Medición de la calidad bajo los estándares de la ISO 9001: Validación de instrumentos de acuerdo con la norma ISO 9001:2015', autor: 'Jesús Guillermo Sotelo Asef, María Concepción Sosa Álvarez, Ernesto Carreón Gallegos', tema: 'Ciencias Económicas y Empresariales', descripcion: 'En la actualidad, dentro de las organizaciones es importante tener bien defi nidos los procesos que en ellas se realizan, así como asegurar la calidad para el cumplimientode los objetivos planeados, estableciendo estrategias y acciones que permitan realizar sus actividades de manera más efi ciente. Para las organizaciones que se encuentrancertificadas por la ISO 9001:2015 es un requisito que se dé cumplimiento a cada elemento que se menciona en ella; dichos elementos, que para efectos del presente libro se denominan variables, son los siguientes: contexto de la organización, liderazgo, planificación, apoyo, operación, evaluación de desempeño y mejora.', url: 'https://www-ebooks7-24-com.bibliodigital.ugc.edu.co/?il=26068' },
    { id: '28', cover: '/2023-08/img/portadas/28.png', titulo: 'El líder que no tenía cargo: Una fábula moderna sobre el liderazgo en la empresa y en la vida', autor: 'Robin Sharma', tema: 'Ciencias Económicas y Empresariales', descripcion: 'Robin Sharma ha compartido durante más de quince años su fórmula para el éxito con las empresas líderes de Fortune 500 y personajes destacados en todo el mundo, una receta que le ha convertido en uno de los asesores de liderazgo más solicitados internacionalmente. Ahora, por primera vez, Sharma comparte sus conocimientos excepcionales con todos sus lectores. Siguiendo sus consejos podrás realizarte como el mejor en tu campo a la vez que contribuirás con tu talento a que tu empresa alcance las metas más altas, algo que resulta esencial en los tiempos turbulentos que estamos viviendo.', url: 'https://ugc.overdrive.com/media/3136392' },
    { id: '29', cover: '/2023-08/img/portadas/29.png', titulo: 'ChatGPT: Ganar Dinero Desde Casa Nunca fue tan Fácil Las 7 mejores fuentes de ingresos pasivos con Inteligencia Artificial (IA)', autor: 'Isabel Flores Sanz', tema: 'Ciencias Económicas y Empresariales', descripcion: 'Si estás buscando una manera fácil y efectiva de generar ingresos pasivos sin tener que dedicar mucho tiempo, ¡este libro es para ti! Así que no esperes más y comienza a generar ingresos adicionales de forma automatizada con la ayuda de ChatGPT. La mejor parte de este libro es que no necesitas tener habilidades técnicas o conocimientos previos en inteligencia artificial para empezar a generar ingresos pasivos. Todo lo que necesitas es una conexión a Internet y una mente abierta para aprender y aplicar lo que te enseño en este libro.', url: 'https://ugc.overdrive.com/media/9667278' },
  ]
};

diccionario.libros.forEach(libro => {
  const nuevaNovedad = crearNovedad(libro.cover, libro.titulo, libro.autor, libro.descripcion, libro.url);
  totalNovedades.appendChild(nuevaNovedad);
});
