const crearNovedad = (cover, titulo, autor, descripcion, url) => {
  const novedad = document.createElement('div');

  const detallesNovedad = `<div class="books" id="books-educacion">
    <img class="cover" src="${cover}" alt="${titulo}">
    <div class="books-details">
        <h2 class="books-titulo">${titulo}</h2>
        <h3 class="books-autor">${autor}</h3>
        <p class="books-descripcion">${descripcion}</p>
        <li class="button-acceso" id="button-acceso-educacion"><a href="${url}" target="_blank">Consulta aquí</a></li>
    </div>`;

  novedad.innerHTML = detallesNovedad;
  return novedad
};

const totalNovedades = document.querySelector("[data-novedades]");

const diccionario = {
  libros: [
    { id: '12', cover: '/2023-08/img/portadas/12.png', titulo: 'Los límites de la interpretación', autor: 'Umberto Eco', tema: 'Ciencias de la Educación', descripcion: 'En este libro audaz, que señala un hito decisivo en su labor crítica,Umberto Eco se convierte en su propio objeto de estudio y analista de sí mismo. Acompañado de Dante, Leopardi y Joyce, e interpretando a los principales hermeneutas de sus obras, Eco replantea cuatro grandes problemas de la semiótica moderna: los «límites de la interpretación», el excesivo dispendio de «energía interpretativa», «los criterios de economía de lectura», y un ataque polémico a la «práctica de la deconstrucción». Trata así de restablecer el equilibrio entre la «intención del lector» y «la intención del autor», al tiempo que demuestra que el principio de la semiosis ilimitada no puede consistir en una derivación incontrolable del sentido. Si bien las interpretaciones de un texto pueden ser infinitas, no todas son buenas, y aunque no sabemos cuáles son las mejores, sí es posible determinar las que resultan totalmente inaceptables.', url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=255016' },
    { id: '19', cover: '/2023-08/img/portadas/19.png', titulo: 'Enseñar con el Mundo en Mente: Aprender STEM resolviendo problemas del mundo real', autor: 'José Manuel Torres Torres', tema: 'Ciencias de la Educación', descripcion: 'En la actualidad, las aulas de clase no han cambiado, son similares a las que existieron en el pasado. El presente libro es una llamada de atención. En estas páginas explico, mediante parábolas o historias cortas, cómo debe cambiar la pedagogía de la educación en Ciencias, Tecnología, Ingeniería y Matemáticas (stem, por sus siglas en inglés). Varias personas, más inteligentes que yo y con mayor trayectoria, han dado su opinión sobre este tema y han escrito obras extensas, incluso han grabado series de videos, pódcasts, etc. ¿Qué podría aportar yo? ¿Por qué usted debería leer este libro?', url: 'https://www-ebooks7-24-com.bibliodigital.ugc.edu.co/?il=25559' },
    { id: '2', cover: '/2023-08/img/portadas/2.png', titulo: 'El teatro La Candelaria Hacia la construcción de los caminos del teatro y la identidad nacional', autor: 'Miriam Dermer Wodnicky', tema: 'Ciencias de la Educación', descripcion: 'El Teatro en Colombia ha sufrido de una serie de dificultades para su consolidación y en consecuencia se constituye en sujeto político mediante su constitución en sujeto cultural- teatral, que mostró una insatisfacción respecto al poco desarrollo que este tema tiene en el Estado Colombiano de manera histórica por su tardía autonomía que se da a partir del año de 1968 con la creación de Colcultura', url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254992' },
    { id: '35', cover: '/2023-08/img/portadas/35.png', titulo: 'Cómo citar: Manual de escritura académica del discurso referido', autor: 'Mireya Cisneros-Estupiñán', tema: 'Ciencias de la Educación', descripcion: 'Este libro ofrece a los profesionales y a los estudiantes de distintas carreras universitarias y posgrados, una guía que facilite la dispendiosa tarea de incorporar, de manera pertinente, reflexiva y efectiva, el proceso de construcción del discurso referido. Respetar la autoría y no cometer plagios aporta seriedad y credibilidad a los escritos', url: 'https://ugc.overdrive.com/media/9342677' },
    { id: '39', cover: '/2023-08/img/portadas/39.png', titulo: 'Curso de escritura creativa', autor: 'Brandon Sanderson', tema: 'Ciencias de la Educación', descripcion: 'Curso de escritura creativa convierte en libro las clases que Brandon Sanderson lleva 16 años impartiendo anualmente en la Universidad Brigham Young, donde estudió. Él mismo dice que nunca ha dejado de darlas porque es un recurso que necesita para seguir creciendo como escritor. El curso se centra en los engranajes de la escritura y tiene un enfoque muy práctico; en él nos habla de la trama, la ambientación y los personajes, pero también de la parte empresarial. Sin embargo, no hace falta querer ser un escritor profesional para leer este libro. Su objetivo es ayudar a cualquier lector a comunicarse mejor y crear buenos hábitos para escribir de forma consistente, con los valiosos consejos de uno de los mayores creadores de nuestro siglo.', url: 'https://ugc.overdrive.com/media/8486503' },
    { id: '42', cover: '/2023-08/img/portadas/42.png', titulo: 'El mito de Sísifo', autor: 'Albert Camus', tema: 'Ciencias de la Educación', descripcion: 'El título del ensayo hace referencia a un personaje de la mitología griega que enfadó a los dioses por su extraordinaria astucia y fue condenado a empujar perpetuamente una piedra enorme montaña arriba. Al llegar a la cima, la piedra volvía a caer hasta el valle, desde donde Sísifo debía volver a empujarla hasta la cumbre, y así eternamente. Por medio de esta alegoría, Camus discute la cuestión del suicidio y el valor de la vida, presentando a Sísifo como imagen del esfuerzo inútil e incesante del hombre. De este modo plantea la filosofía del absurdo, según la cual nuestras vidas son insignificantes y no tienen más valor que el de lo que creamos. Siendo el mundo tan fútil, pregunta Camus, ¿qué alternativa hay al suicidio?', url: 'https://ugc.overdrive.com/media/5928648' },
    { id: '46', cover: '/2023-08/img/portadas/46.png', titulo: '¿Otra historia de Colombia?: De tiempos prehispánicos a hoy: lo fundamental en 12 capítulos', autor: 'Felipe Arias Escobar', tema: 'Ciencias de la Educación', descripcion: 'Cuando creíamos que ya todo estaba dicho sobre la historia de Colombia, llega este libro para de mostrarnos que todavía hay territorios nuevos por explorar. ¿Sabías, por ejemplo, que hubo españoles que estuvieron a favor de la independencia?, ¿que la Conquista fue apoyada por comunidades indígenas?, ¿que la primera huelga obrera en el país fue liderada por una mujer?, ¿o que el gran nivel de resistencia de los ciclistas colombianos se debe a un proceso microevolutivo que data de miles de años atrás?. Esto y mucho más es abordado en estas páginas por Felipe Arias Escobar, quien nos invita a recorrer el pasado desde una perspectiva distinta y a entender el origen de los desafíos que enfrentamos en la actualidad.', url: 'https://ugc.overdrive.com/media/9681940' },
    { id: '59', cover: '/2023-08/img/portadas/59.png', titulo: 'Antología poética', autor: 'Alfonsina Storni', tema: 'Ciencias de la Educación', descripcion: 'Según la crítica, su originalidad cambió el sentido de las letras en Latinoamérica. Su virtuosismo y su cualidad de visionaria, anticipándose a ideas feministas que en su época solo se gestaban, merecen toda nuestra atención y reconocimiento. En esta antología poética, compuesta por ella misma, encontramos, en síntesis subjetiva, desde los poemas románticos de su primera época hasta la última producción animada por una inquietud de renovación. La más exquisita gracia, profundidad, ironía y pasión se revelan a lo largo de sus 180 mejores poesías.', url: 'https://ugc.overdrive.com/media/5426025' },
  ]
};

diccionario.libros.forEach(libro => {
  const nuevaNovedad = crearNovedad(libro.cover, libro.titulo, libro.autor, libro.descripcion, libro.url);
  totalNovedades.appendChild(nuevaNovedad);
});
