const crearNovedad = (cover, titulo, autor, descripcion, url) => {
  const novedad = document.createElement('div');

  const detallesNovedad = `<div class="books" id="books-literatura">
    <img class="cover" src="${cover}" alt="${titulo}">
    <div class="books-details">
        <h2 class="books-titulo">${titulo}</h2>
        <h3 class="books-autor">${autor}</h3>
        <p class="books-descripcion">${descripcion}</p>
        <li class="button-acceso"><a href="${url}" target="_blank">Consulta aquí</a></li>
    </div>`;

  novedad.innerHTML = detallesNovedad;
  return novedad
};

const totalNovedades = document.querySelector("[data-novedades]");

const diccionario = {
  libros: [
    { id: '1', cover: '/2023-08/img/portadas/1.png', titulo: 'Fernando Vallejo a contracorriente', autor: 'Juanita C. Aristizábal', tema: 'Bienestar e Interés general', descripcion: 'Con una mirada aguda y en una prosa clara, Aristizabal escribe sobre Vallejo como tema de análisis y también como una forma de pensar el campo de la literatura latinoamericana y de sus transformaciones durante el último siglo.', url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254907' },
    { id: '25', cover: '/2023-08/img/portadas/25.png', titulo: 'El libro de la risa y el olvido', autor: 'Milan Kundera', tema: 'Bienestar e Interés general', descripcion: 'Una novela ya clásica en torno al olvido, el erotismo y el humor. Mientras Tamina, una joven viuda en el exilio, quiere recuperar sus diarios íntimos para reconstruir con ellos sus cada vez más vagos recuerdos de su vida matrimonial, Mirek, en Bohemia, trata, en cambio, de recobrar unas antiguas cartas de amor para borrar parte de su pasado. Como dice el propio autor, «es una novela sobre Tamina y, en el momento en el que Tamina desaparece de la escena, es una novela para Tamina. Ella es el personaje principal y el principal espectador y todas las demás historias son variaciones de su historia y se reúnen en su vida como en un espejo».', url: 'https://ugc.overdrive.com/media/9665556' },
    { id: '27', cover: '/2023-08/img/portadas/27.png', titulo: 'Ciudad y arquitectura urbana en Colombia, 1980-2017', autor: 'Luis Fernando González Escobar', tema: 'Bienestar e Interés general', descripcion: 'Los pequeños poemas en prosa, también conocido como El spleen de París es una colección de 50 pequeños poemas escritos en prosa poética. La melancolía, el horror al paso del tiempo, el deseo de infinito, la crítica corrosiva contra la religión y la moral, así como la burla contra los ideales que mueven a las personas y una aversión enorme contra la sociedad y la hipocresía que la domina son temas recurrentes en estas poesías.', url: 'https://ugc.overdrive.com/media/5537580' },
    { id: '30', cover: '/2023-08/img/portadas/30.png', titulo: 'El desbarrancadero', autor: 'Fernando Vallejo', tema: 'Bienestar e Interés general', descripcion: 'Cuando Carlos salió del cuarto me acerqué a la cama, me senté a su lado y me incliné sobre él: sus ojos suplicantes se cruzaron con los míos por última vez. ¿qué me quería decir? ¿Que lo ayudara a vivir? ¿O que lo ayudara a morir? A vivir, por supuesto, él nunca quiso morirse.', url: 'https://ugc.overdrive.com/media/1974822' },
    { id: '31', cover: '/2023-08/img/portadas/31.png', titulo: 'La mujer renovada: Una visión nueva y radicalmente positiva de las mujeres en la madurez', autor: 'Louann Brizendine', tema: 'Bienestar e Interés general', descripcion: 'Un libro para descubrir las increíbles posibilidades del cerebro femenino y repensar la mediana edad como una etapa de abundante vitalidad, confianza y sabiduría, por la aclamada autora de El cerebro femenino. Escrita con el rigor de la psiquiatría y la neurociencia, pero con el cuidado y empatía con que se aconseja a un ser querido, La mujer renovada es una guía para navegar por la perimenopausia y la menopausia, así como una ruta hacia un nuevo estado del cerebro y sus increíbles posibilidades.', url: 'https://ugc.overdrive.com/media/9681981' },
    { id: '32', cover: '/2023-08/img/portadas/32.png', titulo: 'Mucho después de medianoche', autor: 'Ray Bradbury', tema: 'Bienestar e Interés general', descripcion: 'Una compliación de relatos maestros. Veintidós cuentos para leer mucho después de medianoche. Bradbury tardó siete años en escribir esta colección de cuentos, una conjura sobre el pasado, el presente y el futuro que encantará a sus millones de lectores. El tiempo pasa, retorna, y se precipita terriblemente hacia adelante en cuentos que muestran otra vez el extraordinario don de Bradbury, capaz de hacernos ver una escena con todos nuestros sentidos. Cada historia es una miniatura y una joya... Una línea basta para revelar un estado de ánimo... Criaturas extrañas se alzan en la noche en un vertiginoso modo poético... Cuentos para una noche de lluvia.', url: 'https://ugc.overdrive.com/media/9557593' },
    { id: '34', cover: '/2023-08/img/portadas/34.png', titulo: 'Prometeo americano: El triunfo y la tragedia de J. Robert Oppenheimer', autor: 'Kai Bird', tema: 'Bienestar e Interés general', descripcion: 'El 16 de julio de 1945, en el desierto de Nuevo México, se detonaba en secreto la primera bomba atómica. Impactado por el poder destructivo de su creación, J. Robert Oppenheimer, director del Proyecto Manhattan, se comprometería desde entonces a luchar contra el desarrollo de la bomba de hidrógeno y contra la guerra nuclear. La biografía definitiva de Oppenheimer, el padre de la bomba atómica y una de las figuras más emblemáticas del siglo XX, en la que se basa la nueva película de Christopher Nolan protagonizada por Cillian Murphy.', url: 'https://ugc.overdrive.com/media/9430470' },
    { id: '36', cover: '/2023-08/img/portadas/36.png', titulo: 'Punto ciego', autor: 'Paula Hawkins', tema: 'Bienestar e Interés general', descripcion: 'Paula Hawkins, la autora de La chica del tren, nos ofrece una novela apasionante en la que descubriremos que hasta el acto mejor intencionado puede tener trágicas consecuencias. Una historia llena de giros y tensión magníficamente escrita por la reina indiscutible del suspense.', url: 'https://ugc.overdrive.com/media/9301619' },
    { id: '37', cover: '/2023-08/img/portadas/37.png', titulo: 'Un asesinato brillante', autor: 'Anthony Horowitz', tema: 'Bienestar e Interés general', descripcion: 'Anthony Horowitz, nos transporta a un laberíntico misterio que encierra otro misterio de la mano de personajes dignos de los mejores clásicos en un escenario contemporáneo impecable y plagado de suspense.', url: 'https://ugc.overdrive.com/media/9022775' },
    { id: '38', cover: '/2023-08/img/portadas/38.png', titulo: 'La inteligencia emocional: Por qué es más importante que el cociente intelectual', autor: 'Daniel Goleman', tema: 'Bienestar e Interés general', descripcion: 'Un libro que te brindará las estrategias para erradicar la violencia y otros rasgos negativos que son la causa de muchos males que aquejan a nuestra familia y nuestra sociedad. Es la inteligencia emocional la que nos permite tomar consciencia de nuestras emociones, comprender los sentimientos de los demás, tolerar las presiones y frustraciones que soportamos en el trabajo, incrementar nuestra capacidad de empatía y nuestras habilidades sociales, y aumentar nuestras posibilidades de desarrollo social.', url: 'https://ugc.overdrive.com/media/8749757' },
    { id: '40', cover: '/2023-08/img/portadas/40.png', titulo: 'Colmillo Blanco', autor: 'Jack London', tema: 'Bienestar e Interés general', descripcion: 'Colmillo Blanco examina el violento mundo de los animales salvajes y el igualmente violento mundo de los humanos', url: 'https://ugc.overdrive.com/media/6460245' },
    { id: '41', cover: '/2023-08/img/portadas/41.png', titulo: 'Vacío emocional: El encuentro con uno mismo y la búsqueda del bienestar', autor: 'Adriana Waisman', tema: 'Bienestar e Interés general', descripcion: '¿Sentís que solo estás pasando por la vida y te dejás llevar por la vorágine de estos tiempos? ¿Lo que estás viviendo -ya sea un problema familiar, una ruptura amorosa o un trabajo poco satisfactorio- te hace sentir estancado o perdido? ¿Actuás como si estuvieras bien cuando en realidad te sentís solo y desconectado?. Puede ser que tengas una buena vida y, sin embargo, por alguna razón no sea suficiente para que te sientas feliz. Las redes sociales, el consumo y las actividades que solo llenan el tiempo se convierten en un escape de lo que te aqueja: el vacío emocional.', url: 'https://ugc.overdrive.com/media/7616213' },
    { id: '43', cover: '/2023-08/img/portadas/43.png', titulo: 'Paraísos artificiales', autor: 'Charles Baudelaire', tema: 'Bienestar e Interés general', descripcion: 'Sin arredrarse ante las conclusiones, multiplicando los puntos de vista, Baudelaire examina sistemáticamente todos los aspectos del consumo del hachís, desde el lado fisiológico y psíquico hasta el lado moral; y aunque aporta una total desenvoltura, como moralista sensible al prestigio del mal y del malditismo, discierne los distintos pasos de esa ebriedad que desemboca en un futuro lleno de amarga desilusión: una necesidad de remordimiento y de alegría, de deseo y de abandono, de denuncia y de pureza. Además de la lucidez del análisis, de su rigor, de la limpidez del estilo, «Los paraísos artificiales» ofrece una muestra de calidad de una inteligencia rara que interpreta las experiencias más diversas con un tacto ejemplar.', url: 'https://ugc.overdrive.com/media/2866271' },
    { id: '44', cover: '/2023-08/img/portadas/44.png', titulo: 'Cerati: La biografía definitiva', autor: 'Juan Morris', tema: 'Bienestar e Interés general', descripcion: 'Por cuatro años y medio, mientras Gustavo Cerati estuvo en coma, todavía quedaba la esperanza de que un día fuera a despertar y por este motivo nadie se animaba a despedirlo. Finalmente, el 4 de septiembre de 2014 llegó la triste noticia de que había fallecido. Esta biografía es un homenaje al músico que cambió para siempre la historia del rock argentino, no solo en su costado musical sino en su faceta más íntima y humana. Con testimonios de los músicos de su banda y de sus familiares,', url: 'https://ugc.overdrive.com/media/4454703' },
    { id: '45', cover: '/2023-08/img/portadas/45.png', titulo: 'Los peligros de fumar en la cama', autor: 'Mariana Enriquez', tema: 'Bienestar e Interés general', descripcion: 'Silvia acaba de llamar. Dice que puedes intentar olvidarla pero que su muerte te perseguirá por siempre. Debes temer; su recuerdo está encendiendo un fuego que devorará tus fachadas y delatará la oscuridad de tu alma. Te consumirá antes de que puedas hacer algo al respecto, antes de que adviertas que la perversidad del mundo nace en ti. Coedición digital Laguna Libros - eLibros. Derechos solo para Colombia y México.', url: 'https://ugc.overdrive.com/media/2812704' },
    { id: '47', cover: '/2023-08/img/portadas/47.png', titulo: 'Hermosos y malditos', autor: 'Francis Scott Fitzgerald', tema: 'Bienestar e Interés general', descripcion: 'Hermosos y malditos narra la historia de una pareja de recién casados, Anthony Patch, de Nueva York, y Gloria Gilbert, de Kansas City, punto de partida que escoge Francis Scott Fitzgerald para describir la decadencia de un matrimonio y de una sociedad hedonista donde la belleza y la fortuna son siempre demasiado fugaces.', url: 'https://ugc.overdrive.com/media/8749752' },
    { id: '48', cover: '/2023-08/img/portadas/48.png', titulo: 'La conspiración', autor: 'Dan Brown', tema: 'Bienestar e Interés general', descripcion: 'Dan Brown transporta a los lectores a la Oficina Nacional de Reconocimiento (NRO), a las plataformas de hielo del círculo polar ártico y a los pasillos del Ala Oeste de la Casa Blanca en un emocionante thriller que recorre los secretos mejor guardados de los servicios secretos norteamericanos.', url: 'https://ugc.overdrive.com/media/2011191' },
    { id: '49', cover: '/2023-08/img/portadas/49.png', titulo: 'Los no lugares', autor: 'Marc Augé', tema: 'Bienestar e Interés general', descripcion: 'Los no lugares no existían en el pasado. Son espacios propiamente contemporáneos de confluencia anónimos, donde personas en tránsito deben instalarse durante algún tiempo de espera, sea a la salida del avión, del tren o del metro que ha de llegar. Apenas permiten un furtivo cruce de miradas entre personas que nunca más se encontrarán. Los no lugares convierten a los ciudadanos en meros elementos de conjuntos que se forman y deshacen al azar y son simbólicos de la condición humana actual y más aún del futuro.', url: 'https://ugc.overdrive.com/media/5361670' },
    { id: '5', cover: '/2023-08/img/portadas/5.png', titulo: 'Hábitos atómicos: Un método sencillo y comprobado para desarrollar buenos hábitos y eliminar los malos', autor: 'James Clear', tema: 'Bienestar e Interés general', descripcion: 'Hábitos atómicos parte de una simple pero poderosa pregunta: ¿Cómo podemos vivir mejor? Sabemos que unos buenos hábitos nos permiten mejorar significativamente nuestra vida, pero con frecuencia nos desviamos del camino: dejamos de hacer ejercicio, comemos mal, dormimos poco, despilfarramos. ¿Por qué es tan fácil caer en los malos hábitos y tan complicado seguir los buenos? James Clear nos brinda fantásticas ideas basadas en investigaciones científicas, que le permiten revelarnos cómo podemos transformar pequeños hábitos cotidianos para cambiar nuestra vida y mejorarla', url: 'https://biblioteca.ugc.edu.co/cgi-bin/koha/opac-detail.pl?biblionumber=254956' },
    { id: '50', cover: '/2023-08/img/portadas/50.png', titulo: 'El ferrocarril subterráneo', autor: 'Colson Whitehead', tema: 'Bienestar e Interés general', descripcion: 'Whitehead nos brinda una historia universal, onírica y a la vez brutalmente realista, sobre la libertad y las ilusiones truncadas, que nos habla de la fuerza sobrehumana que emerge ante la determinación de cambiar el propio destino.', url: 'https://ugc.overdrive.com/media/3349596' },
    { id: '51', cover: '/2023-08/img/portadas/51.png', titulo: 'La sombra sobre Innsmouth', autor: 'H. P. Lovecraft', tema: 'Bienestar e Interés general', descripcion: 'Esta fue la única obra de Lovecraft publicada de esta forma durante su vida ya que lo habitual era que sus novelas se publicasen por entregas en revistas. La historia se ubica en el ficticio y decadente pueblo de Innsmouth, en Massachussets, y narra el descubrimiento de los seres híbridos mitad humanos mitad peces que lo habitan.', url: 'https://ugc.overdrive.com/media/2441336' },
    { id: '52', cover: '/2023-08/img/portadas/52.png', titulo: 'La declaración de Randolph Carter y otros hechos inenarrables', autor: 'H. P. Lovecraft', tema: 'Bienestar e Interés general', descripcion: 'Desde tiempos inmemoriales, la humanidad ha mirado a las estrellas, sobrecogida por los misterios que puede esconder el infinito vacío que las separa. Entonces, para evitar el desasosiego, baja la mirada, pero debajo del horizonte se encuentra con el océano, cuyas profundidades terribles, oscuras, ignotas, esconden secretos abismales de tiempos remotos. En el infinito azul se pueden esconder las más temibles criaturas y las más milenarias ciudades sumergidas. En ese momento, invadida por el más puro terror, se vuelca hacia el sueño, intenta escapar. Pero solo se encuentra frente a frente, una vez más, con lo desconocido, pues más allá de la barrera del sueño también le esperan mundos indescriptibles de los que solo puede obtener los más ínfimos vistazos.', url: 'https://ugc.overdrive.com/media/4817767' },
    { id: '53', cover: '/2023-08/img/portadas/53.png', titulo: 'Ana de las tejas verdes', autor: 'Lucy Maud Montgomery', tema: 'Bienestar e Interés general', descripcion: 'Marilla Cuthbert y Matthew Cuthbert, dos hermanos de mediana edad que viven juntos en Tejas Verdes, una granja en un pueblecito llamado Avonlea, en la Isla del Príncipe Eduardo, deciden adoptar a un muchacho huérfano de un orfanato de Nueva Escocia para que les ayude con la granja. Debido a una serie de desgracias y malentendidos, la que termina en Tejas Verdes es una precoz e inteligente chica de once años llamada Ana Shirley. Ana es brillante y perspicaz, impaciente por ser complaciente, pero descontenta con su nombre, su piel pálida llena de pecas, y sobre todo con sus largas trenzas de pelo rojo. Ana es una niña con una imaginación muy fértil, que llenará de alegría las vidas de los dos hermanos así como del resto de habitantes de Avonlea.', url: 'https://ugc.overdrive.com/media/6281577' },
    { id: '54', cover: '/2023-08/img/portadas/54.png', titulo: 'El coloso de Nueva York', autor: 'Colson Whitehead', tema: 'Bienestar e Interés general', descripcion: 'Un tributo a la ciudad que nunca duerme, un homenaje literario al paisaje urbano y al ambiente fascinante y febril que dibujan sus habitantes. Whitehead pone de manifiesto que Nueva York es una ciudad viva, una ciudad que representa la modernidad y el progreso, y como tal está sujeta a todo tipo de cambios, algunos de ellos, como ya se ha demostrado, de terribles consecuencias.', url: 'https://ugc.overdrive.com/media/3358857' },
    { id: '55', cover: '/2023-08/img/portadas/55.png', titulo: '13 Relatos', autor: 'Edgar Allan Poe', tema: 'Bienestar e Interés general', descripcion: 'En esta recopilación de 13 relatos de Edgar Allan Poe nos encontramos con historias de terror o detectivescas, de quien ha sido llamado un genio de la literatura, pues aunque su vida fue corta, ya que falleció a los cuarenta años, fue él, quien dio un vuelco a la historia de la literatura estadounidense. Fue primero en muchos aspectos: fue un maestro del cuento, inventó el relato detectivesco, incursionó en el género de la ciencia ficción y dominó magistralmente la escritura de historias de terror. La importancia de su obra y estilo es reconocida nacional e internacionalmente, ya que influyó en grandes escritores como Baudelaire, Dostoyevski, Faulkner, Kafka, Guy de Maupassant, Borges, Cortázar y Darío.', url: 'https://ugc.overdrive.com/media/9725702' },
    { id: '56', cover: '/2023-08/img/portadas/56.png', titulo: 'Meditaciones de cine', autor: 'Quentin Tarantino', tema: 'Bienestar e Interés general', descripcion: 'Meditaciones de cine es, a la vez, crítica cinematográfica, teoría del cine, reportajeliterario y unas memorias formidables, a la altura de clásicos del género como los de Hitchcock y Truffaut o Luis Buñuel.', url: 'https://ugc.overdrive.com/media/9399239' },
    { id: '57', cover: '/2023-08/img/portadas/57.png', titulo: 'El poder de las palabras: Cómo cambiar tu cerebro (y tu vida) conversando', autor: 'Mariano Sigman', tema: 'Bienestar e Interés general', descripcion: 'Es posible cambiar, en cualquier momento de la vida, nuestras ideas más arraigadas, nuestra forma de pensar y también nuestra experiencia emocional. Para lograrlo es suficiente una herramienta sencilla y extremadamente efectiva en la transformación de nuestro cerebro: el buen uso de la conversación.', url: 'https://ugc.overdrive.com/media/9263673' },
    { id: '58', cover: '/2023-08/img/portadas/58.png', titulo: 'La mejor cosa que nunca tendrás', autor: 'Efraim Medina Reyes', tema: 'Bienestar e Interés general', descripcion: 'En estas páginas se siente no solo la escritura de quien ha hecho una obra honesta –que no se ahorra, que no cree en lo políticamente correcto ni en la reinante cultura de la cancelación– y que ha escrito con las tripas. El corazón palpita y la poesía aparece y uno se pregunta cuál es esa mejor cosa que nunca tendrás y entiende que es eso, el tiempo, lo que no podemos comprender por estar viviéndolo y se nos escapa para aparecer, mucho tiempo después, por gracia de la literatura en libros tan notables y hermosos como este.', url: 'https://ugc.overdrive.com/media/9300997' },
    { id: '60', cover: '/2023-08/img/portadas/60.png', titulo: 'El baile de las luciérnagas', autor: 'Kristin Hannah', tema: 'Bienestar e Interés general', descripcion: 'En el caluroso verano de 1974, Kate Mularkey ha decido aceptar su papel de cero a la izquierda en la vida social de su instituto. Hasta que, para su sorpresa, «la chica más guay del mundo» se muda al otro lado de su calle y quiere ser su amiga. Tully Hart parece tenerlo todo: belleza, inteligencia y ambición. No pueden ser más distintas. Kate, destinada a pasar inadvertida, con una familia cariñosa pero que la avergüenza a cada momento, y Tully, envuelta en glamour y misterio aunque poseedora de un secreto que la está destrozando. Contra todo pronóstico, se hacen inseparables y sellan un pacto para ser mejores amigas para siempre.', url: 'https://ugc.overdrive.com/media/6201481' },
    { id: '61', cover: '/2023-08/img/portadas/61.png', titulo: 'Lolita', autor: 'Vladimir Nabokov', tema: 'Bienestar e Interés general', descripcion: 'Considerada como una obra maestra indiscutible de la literatura universal. La historia de la obsesión de Humbert Humbert, un profesor cuarentón, por la doceañera Lolita es una extraordinaria novela de amor en la que intervienen dos componentes explosivos: la atracción «perversa» por las nínfulas y el incesto. Un itinerario a través de la locura y la muerte, que desemboca en una estilizadísima violencia, narrado, a la vez con autoironía y lirismo desenfrenado, por el propio Humbert Humbert.', url: 'https://ugc.overdrive.com/media/8818880' },
    { id: '64', cover: '/2023-08/img/portadas/64.png', titulo: 'Lejos de Luisiana', autor: 'Luz Gabás', tema: 'Bienestar e Interés general', descripcion: 'En unos tiempos tan convulsos, Suzette Girard e Ishcate, indio de la tribu kaskaskia, librarán su propia batalla: preservar su amor de las amenazas del mundo que les ha tocado vivir. Su nueva obra Lejos de Luisiana, ganadora del Premio Planeta 2022, es una novela magistral y un gran fresco histórico sobre la aventura de España en el corazón de Norteamérica.', url: 'https://ugc.overdrive.com/media/9404706' },
  ]
};

diccionario.libros.forEach(libro => {
  const nuevaNovedad = crearNovedad(libro.cover, libro.titulo, libro.autor, libro.descripcion, libro.url);
  totalNovedades.appendChild(nuevaNovedad);
});
